dist: trusty
sudo: required
language: ruby
services:
  - postgresql

env:
  - ADAPTER=SQLite
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
jobs:
  include:
    - rvm: 2.4
      env:
        - ADAPTER=PostgreSQL
script: ci/travis
