#!/usr/bin/env bash
set -euo pipefail

export DB_ADAPTER=${DB_ADAPTER:-mysql}
if [[ "${DB_ADAPTER}" == "mysql" ]]; then
  mysql -e 'CREATE DATABASE bulk_insert_test;'
fi

cd test/dummy
bundle exec rake db:test:load
cd -
