#!/usr/bin/env bash
set -euo pipefail

export DB_ADAPTER=${DB_ADAPTER:-mysql}

case $DB_ADAPTER in
  mysql)
    mysql -e 'CREATE DATABASE bulk_insert_test;'
    ;;
  postgresql)
    psql -c 'create database bulk_insert_test;' -U postgres
    ;;
esac

cd test/dummy
bundle exec rake db:test:load
cd -
